# -*- coding: utf-8 -*-
"""
================================================================================
V3 無濾網回測腳本 (No Buy Filter Backtest)
================================================================================
測試 V3 模型在取消 Signal_Buy_Filter 限制下的交易績效。
每一天都可以考慮買進，而非僅在 Donchian 突破日。

用途：
- 評估 Buy Filter 對績效的貢獻度
- 比較有/無濾網的交易次數與勝率差異

作者：Phil Liang (Generated by Gemini)
日期：2025-12-08
================================================================================
"""

import os
import sys
import pickle
import argparse
from datetime import datetime

# Windows UTF-8 設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
from stable_baselines3 import PPO

# 中文字型設定
plt.rcParams['font.sans-serif'] = ['Microsoft JhengHei', 'SimHei', 'Arial Unicode MS']
plt.rcParams['axes.unicode_minus'] = False

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
V3_MODELS_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v3')
RESULTS_PATH = os.path.join(PROJECT_PATH, 'results_backtest_v3_no_filter')
CACHE_DIR = os.path.join(PROJECT_PATH, 'data', 'processed')

DEFAULT_START_DATE = '2023-01-01'  # 預設回測起始日
DEFAULT_END_DATE = None  # None 表示到最新資料
INITIAL_CAPITAL = 1_000_000


def parse_args():
    """解析命令列參數"""
    parser = argparse.ArgumentParser(
        description='V3 無濾網回測腳本 - 支援自訂回測日期範圍',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
使用範例:
  python backtest_v3_no_filter.py                           # 使用預設日期 (2023-01-01 至今)
  python backtest_v3_no_filter.py --start 2022-01-01        # 從 2022-01-01 開始回測
  python backtest_v3_no_filter.py --end 2024-06-30          # 回測到 2024-06-30
  python backtest_v3_no_filter.py --start 2021-01-01 --end 2023-12-31  # 指定完整日期範圍
        '''
    )
    parser.add_argument(
        '--start', 
        type=str, 
        default=DEFAULT_START_DATE,
        help=f'回測開始日期 (YYYY-MM-DD 格式，預設: {DEFAULT_START_DATE})'
    )
    parser.add_argument(
        '--end', 
        type=str, 
        default=DEFAULT_END_DATE,
        help='回測結束日期 (YYYY-MM-DD 格式，預設: 最新資料)'
    )
    return parser.parse_args()


# =============================================================================
# 無濾網回測器
# =============================================================================
class NoFilterBacktester:
    """
    無濾網回測器：每天都考慮買進訊號，不受 Signal_Buy_Filter 限制
    """
    def __init__(self, buy_model, sell_model, initial_capital=1_000_000):
        self.buy_model = buy_model
        self.sell_model = sell_model
        self.initial_capital = initial_capital
        self.trades = []
        self.equity_curve = []
        self.buy_signals = []
        self.sell_signals = []
    
    def run(self, df: pd.DataFrame, feature_cols: list) -> dict:
        """執行無濾網回測"""
        capital = self.initial_capital
        position = None
        
        features = df[feature_cols].values.astype(np.float32)
        close_prices = df['Close'].values
        dates = df.index
        
        print(f"[Backtest] Period: {dates[0].strftime('%Y-%m-%d')} ~ {dates[-1].strftime('%Y-%m-%d')}")
        print(f"[Backtest] Data points: {len(df)}")
        print(f"[Backtest] Initial capital: ${capital:,.0f}")
        print("[Backtest] Mode: No Filter (daily buy check)")
        
        for i in range(len(df)):
            date = dates[i]
            price = close_prices[i]
            
            # 記錄每日淨值
            if position is not None:
                current_value = capital + position['shares'] * price
            else:
                current_value = capital
            self.equity_curve.append({'date': date, 'value': current_value})
            
            # 處理 NaN
            obs = np.nan_to_num(features[i], nan=0.0, posinf=1.0, neginf=-1.0)
            
            # =====================================================================
            # 持有中：檢查賣出
            # =====================================================================
            if position is not None:
                hold_days = i - position['buy_idx']
                current_return = price / position['buy_price']
                
                # Sell Agent 觀察 (Features + Current Return)
                sell_obs = np.concatenate([obs, [current_return]]).astype(np.float32)
                action, _ = self.sell_model.predict(sell_obs.reshape(1, -1), deterministic=True)
                
                # 停損/停利/AI決策/超時
                stop_loss = current_return < 0.92  # -8% 停損
                should_sell = action[0] == 1 or stop_loss or hold_days >= 120
                
                if should_sell:
                    sell_value = position['shares'] * price
                    profit = sell_value - position['shares'] * position['buy_price']
                    capital += sell_value
                    
                    self.trades.append({
                        'buy_date': position['buy_date'],
                        'buy_price': position['buy_price'],
                        'sell_date': date,
                        'sell_price': price,
                        'return': current_return - 1,
                        'profit': profit,
                        'hold_days': hold_days
                    })
                    self.sell_signals.append((date, price))
                    position = None
            
            # =====================================================================
            # 空手：每天都檢查買入 (無濾網)
            # =====================================================================
            elif position is None:
                buy_obs = obs.reshape(1, -1)
                action, _ = self.buy_model.predict(buy_obs, deterministic=True)
                
                if action[0] == 1:  # Buy
                    invest_amount = capital * 0.9
                    shares = int(invest_amount / price)
                    
                    if shares > 0:
                        cost = shares * price
                        capital -= cost
                        
                        position = {
                            'shares': shares,
                            'buy_price': price,
                            'buy_date': date,
                            'buy_idx': i
                        }
                        self.buy_signals.append((date, price))
        
        return self._calculate_metrics(df)
    
    def _calculate_metrics(self, df: pd.DataFrame) -> dict:
        """計算績效指標"""
        if not self.equity_curve:
            return {}
        
        equity_df = pd.DataFrame(self.equity_curve)
        equity_df['date'] = pd.to_datetime(equity_df['date'])
        equity_df.set_index('date', inplace=True)
        
        initial = self.initial_capital
        final = equity_df['value'].iloc[-1]
        total_return = (final - initial) / initial
        
        days = (equity_df.index[-1] - equity_df.index[0]).days
        years = days / 365.0
        annualized_return = (1 + total_return) ** (1 / years) - 1 if years > 0 else 0
        
        daily_returns = equity_df['value'].pct_change().dropna()
        if len(daily_returns) > 0 and daily_returns.std() > 0:
            sharpe = (daily_returns.mean() * 252 - 0.02) / (daily_returns.std() * np.sqrt(252))
        else:
            sharpe = 0
        
        rolling_max = equity_df['value'].cummax()
        drawdown = (equity_df['value'] - rolling_max) / rolling_max
        max_drawdown = drawdown.min()
        
        if self.trades:
            wins = sum(1 for t in self.trades if t['return'] > 0)
            win_rate = wins / len(self.trades)
            avg_return = np.mean([t['return'] for t in self.trades])
            avg_hold_days = np.mean([t['hold_days'] for t in self.trades])
        else:
            win_rate = 0
            avg_return = 0
            avg_hold_days = 0
        
        return {
            'initial_capital': initial,
            'final_value': final,
            'total_return': total_return,
            'annualized_return': annualized_return,
            'sharpe_ratio': sharpe,
            'max_drawdown': max_drawdown,
            'total_trades': len(self.trades),
            'win_rate': win_rate,
            'avg_return': avg_return,
            'avg_hold_days': avg_hold_days,
            'equity_df': equity_df
        }


# =============================================================================
# 主程式
# =============================================================================
def main():
    # 解析命令列參數
    args = parse_args()
    
    # 驗證日期格式
    try:
        start_date = pd.Timestamp(args.start)
    except Exception as e:
        print(f"[Error] Invalid start date format: {args.start}")
        print("Please use YYYY-MM-DD format, e.g.: 2023-01-01")
        sys.exit(1)
    
    end_date = None
    if args.end:
        try:
            end_date = pd.Timestamp(args.end)
        except Exception as e:
            print(f"[Error] Invalid end date format: {args.end}")
            print("Please use YYYY-MM-DD format, e.g.: 2024-12-31")
            sys.exit(1)
        
        if end_date <= start_date:
            print(f"[Error] End date ({args.end}) must be greater than start date ({args.start})")
            sys.exit(1)
    
    print("=" * 60)
    print("V3 No Filter Backtest")
    print("=" * 60)
    print(f"  Start date: {args.start}")
    print(f"  End date:   {args.end if args.end else 'Latest data'}")
    
    # 建立輸出目錄
    os.makedirs(RESULTS_PATH, exist_ok=True)
    
    # =========================================================================
    # 載入模型
    # =========================================================================
    print("\n[Model] Loading V3 models...")
    buy_path = os.path.join(V3_MODELS_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(V3_MODELS_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        print(f"[Error] Model not found: {buy_path}")
        print("Please run train_v3_models.py first")
        sys.exit(1)
    
    buy_model = PPO.load(buy_path)
    sell_model = PPO.load(sell_path)
    print("  Models loaded successfully")
    
    # =========================================================================
    # 載入/計算特徵資料
    # =========================================================================
    print("\n[Data] Preparing backtest data...")
    import ptrl_hybrid_system as hybrid
    import twii_model_registry_multivariate as lstm_1d_module
    import twii_model_registry_5d as lstm_5d_module
    
    # [v3.0] 使用回測 start_date 來選擇 LSTM 模型 (避免資料洩漏)
    print(f"\n[LSTM] Loading models with cutoff_date: {start_date.date()}")
    print(f"[LSTM] Only models with train_end < {start_date.date()} will be considered")
    
    meta_1d = lstm_1d_module.select_best_model(start_date.date())
    if meta_1d is None:
        print("[Error] No valid T+1 model found for the specified date range")
        sys.exit(1)
    model_1d, scaler_feat_1d, scaler_tgt_1d, _ = lstm_1d_module.load_artifacts(
        meta_1d['train_start'], meta_1d['train_end'])
    print(f"  ✅ T+1 Model: {meta_1d['train_start']} ~ {meta_1d['train_end']}")
    
    meta_5d = lstm_5d_module.select_best_model(start_date.date())
    if meta_5d is None:
        print("[Error] No valid T+5 model found for the specified date range")
        sys.exit(1)
    model_5d, scaler_feat_5d, scaler_tgt_5d, _ = lstm_5d_module.load_artifacts(
        meta_5d['train_start'], meta_5d['train_end'])
    print(f"  ✅ T+5 Model: {meta_5d['train_start']} ~ {meta_5d['train_end']}")
    
    # 注入到 hybrid 模組
    hybrid._LSTM_MODELS.update({
        'model_1d': model_1d, 'scaler_feat_1d': scaler_feat_1d,
        'scaler_tgt_1d': scaler_tgt_1d, 'meta_1d': meta_1d,
        'model_5d': model_5d, 'scaler_feat_5d': scaler_feat_5d,
        'scaler_tgt_5d': scaler_tgt_5d, 'meta_5d': meta_5d, 'loaded': True
    })
    
    cache_path = os.path.join(CACHE_DIR, "_TWII_features.pkl")
    if os.path.exists(cache_path):
        print(f"  [Cache] Loading: {cache_path}")
        with open(cache_path, 'rb') as f:
            twii_full_df = pickle.load(f)
    else:
        print("  [Compute] Loading from local CSV...")
        # [Modify] 使用本地資料載入函數
        twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
        twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=True)
    
    # 分割回測資料 (使用命令列指定的日期範圍)
    twii_backtest_df = twii_full_df[twii_full_df.index >= start_date]
    if end_date:
        twii_backtest_df = twii_backtest_df[twii_backtest_df.index <= end_date]
    
    if len(twii_backtest_df) == 0:
        print(f"[Error] No data in specified date range")
        print(f"  Available range: {twii_full_df.index[0].strftime('%Y-%m-%d')} ~ {twii_full_df.index[-1].strftime('%Y-%m-%d')}")
        sys.exit(1)
    
    print(f"  Period: {twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}")
    print(f"  Data points: {len(twii_backtest_df)}")
    
    # =========================================================================
    # 執行回測
    # =========================================================================
    print("\n[Backtest] Starting no-filter backtest...")
    backtester = NoFilterBacktester(buy_model, sell_model, INITIAL_CAPITAL)
    metrics = backtester.run(twii_backtest_df, hybrid.FEATURE_COLS)
    
    # =========================================================================
    # 計算 Benchmark (Buy & Hold) 績效指標
    # =========================================================================
    equity_df = metrics['equity_df']
    bench_slice = twii_full_df.loc[equity_df.index[0]:equity_df.index[-1]]['Close']
    bench_normalized = bench_slice / bench_slice.iloc[0] * INITIAL_CAPITAL
    
    bench_initial = INITIAL_CAPITAL
    bench_final = bench_normalized.iloc[-1]
    bench_total_return = (bench_final - bench_initial) / bench_initial
    
    days = (bench_slice.index[-1] - bench_slice.index[0]).days
    years = days / 365.0
    bench_annualized = (1 + bench_total_return) ** (1 / years) - 1 if years > 0 else 0
    
    bench_daily_returns = bench_normalized.pct_change().dropna()
    if len(bench_daily_returns) > 0 and bench_daily_returns.std() > 0:
        bench_sharpe = (bench_daily_returns.mean() * 252 - 0.02) / (bench_daily_returns.std() * np.sqrt(252))
    else:
        bench_sharpe = 0
    
    bench_rolling_max = bench_normalized.cummax()
    bench_drawdown = (bench_normalized - bench_rolling_max) / bench_rolling_max
    bench_max_dd = bench_drawdown.min()
    
    # =========================================================================
    # 印出績效 (Side by Side)
    # =========================================================================
    print("\n" + "=" * 70)
    print("Performance Comparison: V3 (No Filter) vs Buy & Hold")
    print("=" * 70)
    print(f"{'Metric':<20} {'V3 (No Filter)':>20} {'Buy & Hold':>20}")
    print("-" * 70)
    print(f"{'Initial Capital':<20} ${metrics['initial_capital']:>18,.0f} ${bench_initial:>18,.0f}")
    print(f"{'Final Value':<20} ${metrics['final_value']:>18,.0f} ${bench_final:>18,.0f}")
    print(f"{'Total Return':<20} {metrics['total_return']*100:>19.2f}% {bench_total_return*100:>19.2f}%")
    print(f"{'Annualized Return':<20} {metrics['annualized_return']*100:>19.2f}% {bench_annualized*100:>19.2f}%")
    print(f"{'Sharpe Ratio':<20} {metrics['sharpe_ratio']:>20.2f} {bench_sharpe:>20.2f}")
    print(f"{'Max Drawdown':<20} {metrics['max_drawdown']*100:>19.2f}% {bench_max_dd*100:>19.2f}%")
    print("-" * 70)
    print(f"{'Trades':<20} {metrics['total_trades']:>20}")
    print(f"{'Win Rate':<20} {metrics['win_rate']*100:>19.1f}%")
    print(f"{'Avg Return/Trade':<20} {metrics['avg_return']*100:>19.2f}%")
    print(f"{'Avg Hold Days':<20} {metrics['avg_hold_days']:>20.1f}")
    print("=" * 70)
    
    # =========================================================================
    # 視覺化
    # =========================================================================
    fig, axes = plt.subplots(2, 1, figsize=(14, 10))
    
    # 子圖 1: Portfolio Value vs Benchmark
    ax1 = axes[0]
    
    ax1.plot(equity_df.index, equity_df['value'], label='V3 (No Filter)', color='blue', linewidth=2)
    ax1.plot(bench_normalized.index, bench_normalized.values, 
             label='^TWII Buy & Hold', color='gray', linewidth=1.5, alpha=0.7)
    
    date_range_str = f"{twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}"
    ax1.set_title(f'V3 No Filter vs Buy & Hold ({date_range_str})', fontsize=14)
    ax1.set_ylabel('Portfolio Value ($)')
    ax1.legend(loc='upper left')
    ax1.grid(True, alpha=0.3)
    
    # 績效摘要文字框 (Side by Side)
    summary_text = (
        f"{'Metric':<12} {'V3':>12} {'B&H':>12}\n"
        f"{'-'*38}\n"
        f"{'Final':.<12} ${metrics['final_value']/1e6:>10.2f}M ${bench_final/1e6:>10.2f}M\n"
        f"{'Return':.<12} {metrics['total_return']*100:>11.1f}% {bench_total_return*100:>11.1f}%\n"
        f"{'Annual':.<12} {metrics['annualized_return']*100:>11.1f}% {bench_annualized*100:>11.1f}%\n"
        f"{'Sharpe':.<12} {metrics['sharpe_ratio']:>12.2f} {bench_sharpe:>12.2f}\n"
        f"{'Max DD':.<12} {metrics['max_drawdown']*100:>11.1f}% {bench_max_dd*100:>11.1f}%\n"
        f"{'-'*38}\n"
        f"{'Trades':.<12} {metrics['total_trades']:>12}\n"
        f"{'Win Rate':.<12} {metrics['win_rate']*100:>11.1f}%"
    )
    
    # 在圖表右下角加入績效摘要
    props = dict(boxstyle='round,pad=0.5', facecolor='white', alpha=0.9, edgecolor='gray')
    ax1.text(0.98, 0.03, summary_text, transform=ax1.transAxes, fontsize=9,
             verticalalignment='bottom', horizontalalignment='right',
             bbox=props, family='monospace')
    
    # 子圖 2: Price with Signals
    ax2 = axes[1]
    price_slice = twii_backtest_df['Close']
    ax2.plot(price_slice.index, price_slice.values, label='^TWII Close', color='black', linewidth=1)
    
    if backtester.buy_signals:
        buy_dates, buy_prices = zip(*backtester.buy_signals)
        ax2.scatter(buy_dates, buy_prices, marker='^', color='red', s=100, label='Buy', zorder=5)
    
    if backtester.sell_signals:
        sell_dates, sell_prices = zip(*backtester.sell_signals)
        ax2.scatter(sell_dates, sell_prices, marker='v', color='green', s=100, label='Sell', zorder=5)
    
    ax2.set_title('Trade Signals (No Filter)', fontsize=14)
    ax2.set_ylabel('Price')
    ax2.set_xlabel('Date')
    ax2.legend(loc='upper left')
    ax2.grid(True, alpha=0.3)
    
    plt.tight_layout()
    
    # 儲存圖表 (檔名包含日期範圍)
    start_str = twii_backtest_df.index[0].strftime('%Y%m%d')
    end_str = twii_backtest_df.index[-1].strftime('%Y%m%d')
    save_path = os.path.join(RESULTS_PATH, f'backtest_v3_no_filter_{start_str}_{end_str}.png')
    plt.savefig(save_path, dpi=150, bbox_inches='tight')
    print(f"\n[Output] Chart saved: {save_path}")
    plt.close()
    
    # =========================================================================
    # 儲存績效摘要 CSV (Side by Side)
    # =========================================================================
    metrics_df = pd.DataFrame({
        'Metric': ['Initial_Capital', 'Final_Value', 'Total_Return_Pct', 'Annualized_Return_Pct', 
                   'Sharpe_Ratio', 'Max_Drawdown_Pct', 'Trades', 'Win_Rate_Pct', 'Avg_Return_Pct', 'Avg_Hold_Days'],
        'V3_No_Filter': [metrics['initial_capital'], metrics['final_value'], metrics['total_return']*100,
                         metrics['annualized_return']*100, metrics['sharpe_ratio'], metrics['max_drawdown']*100,
                         metrics['total_trades'], metrics['win_rate']*100, metrics['avg_return']*100, metrics['avg_hold_days']],
        'Buy_Hold': [bench_initial, bench_final, bench_total_return*100, bench_annualized*100,
                     bench_sharpe, bench_max_dd*100, 'N/A', 'N/A', 'N/A', 'N/A']
    })
    metrics_path = os.path.join(RESULTS_PATH, f'metrics_v3_no_filter_{start_str}_{end_str}.csv')
    metrics_df.to_csv(metrics_path, index=False, encoding='utf-8-sig')
    print(f"[Output] Metrics CSV: {metrics_path}")
    
    # =========================================================================
    # 儲存交易明細
    # =========================================================================
    if backtester.trades:
        trades_df = pd.DataFrame(backtester.trades)
        trades_path = os.path.join(RESULTS_PATH, f'trades_v3_no_filter_{start_str}_{end_str}.csv')
        trades_df.to_csv(trades_path, index=False)
        print(f"[Output] Trades CSV: {trades_path}")
        
        print("\n[Trades] Last 5 trades:")
        print(trades_df.tail().to_string(index=False))
    
    print("\n" + "=" * 60)
    print("Backtest completed!")
    print("=" * 60)


if __name__ == "__main__":
    main()
