# -*- coding: utf-8 -*-
"""
================================================================================
Daily Operations for Rolling LSTM V4 Strategy (with Daily LSTM Retraining)
================================================================================
每日維運腳本 - Rolling LSTM V4 + 每日 LSTM 重訓版

特點：
1. 每日重訓 LSTM 模型 (與 daily_ops_dual.py 相同)
2. 使用 Rolling LSTM 訓練的 RL 模型 (models_hybrid_v4_rolling/)
3. 適合比較「每日重訓」vs「固定模型」的差異

與 daily_ops_v4_rolling.py 差異：
- 執行 Step 1 (LSTM 每日重訓)
- 執行時間約 15-20 分鐘 (因 LSTM 訓練)

作者：Phil Liang (Generated by Gemini)
日期：2025-12-12
================================================================================
"""

import os
import sys
import shutil
import pickle
import subprocess
import json
import glob
from datetime import datetime, timedelta

# 設定 UTF-8 輸出
sys.stdout.reconfigure(encoding='utf-8')
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import numpy as np
import pandas as pd
from tensorflow import keras

# =============================================================================
# 引用主系統
# =============================================================================
import ptrl_hybrid_system as core_system

# =============================================================================
# 設定路徑
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
DAILY_RUNS_PATH = os.path.join(PROJECT_PATH, 'daily_runs_rolling_retrain')

# LSTM 訓練腳本
SCRIPT_5D = "twii_model_registry_5d.py"
SCRIPT_1D = "twii_model_registry_multivariate.py"

# LSTM 模型預設輸出路徑
DEFAULT_LSTM_5D_DIR = os.path.join(PROJECT_PATH, 'saved_models_5d')
DEFAULT_LSTM_1D_DIR = os.path.join(PROJECT_PATH, 'saved_models_multivariate')

# Rolling RL 模型路徑 (使用 Rolling LSTM 訓練的模型)
ROLLING_RL_PATH = os.path.join(PROJECT_PATH, 'models_hybrid_v4_rolling')


# =============================================================================
# Step 0: 建立當日專屬工作區
# =============================================================================
def create_daily_workspace(date_str: str) -> dict:
    daily_path = os.path.join(DAILY_RUNS_PATH, date_str)
    paths = {
        'root': daily_path,
        'lstm_models': os.path.join(daily_path, 'lstm_models'),
        'lstm_5d': os.path.join(daily_path, 'lstm_models', 'saved_models_5d'),
        'lstm_1d': os.path.join(daily_path, 'lstm_models', 'saved_models_multivariate'),
        'cache': os.path.join(daily_path, 'cache'),
        'reports': os.path.join(daily_path, 'reports'),
    }
    for key, path in paths.items():
        os.makedirs(path, exist_ok=True)
    print(f"[Workspace] 建立當日工作區: {daily_path}")
    return paths


# =============================================================================
# Step 1: LSTM 全量重訓與封存 (與 daily_ops_dual.py 相同)
# =============================================================================
def train_and_archive_lstm(workspace: dict, end_date: str):
    print("\n" + "=" * 60)
    print("📚 Step 1: LSTM 全量重訓與封存 (每日重訓)")
    print("=" * 60)
    
    # 動態計算起始日期 (與 daily_ops_dual.py 一致)
    end_dt = datetime.strptime(end_date, '%Y-%m-%d')
    start_5d = (end_dt - timedelta(days=2200)).strftime('%Y-%m-%d')
    start_1d = (end_dt - timedelta(days=2000)).strftime('%Y-%m-%d')
    
    # 啟用全量學習：split_ratio = 0.99
    split_ratio = "0.99"
    
    # 1. 執行 T+5 訓練
    print(f"\n[Training] T+5 Model ({start_5d} ~ {end_date}, split={split_ratio})...")
    script_5d_path = os.path.join(PROJECT_PATH, SCRIPT_5D)
    cmd_5d = [sys.executable, script_5d_path, "train", "--start", start_5d, "--end", end_date, "--split_ratio", split_ratio]
    try:
        subprocess.run(cmd_5d, check=True, timeout=1200, cwd=PROJECT_PATH)
        print("[Training] ✅ T+5 訓練完成")
    except subprocess.CalledProcessError as e:
        print(f"[Error] T+5 訓練失敗: {e}")
        return False
    except FileNotFoundError:
        print(f"[Error] 找不到訓練腳本: {script_5d_path}")
        return False
    except Exception as e:
        print(f"[Error] 執行錯誤: {e}")
        return False

    # 2. 執行 T+1 訓練
    print(f"\n[Training] T+1 Model ({start_1d} ~ {end_date}, split={split_ratio})...")
    script_1d_path = os.path.join(PROJECT_PATH, SCRIPT_1D)
    cmd_1d = [sys.executable, script_1d_path, "train", "--start", start_1d, "--end", end_date, "--split_ratio", split_ratio]
    try:
        subprocess.run(cmd_1d, check=True, timeout=1200, cwd=PROJECT_PATH)
        print("[Training] ✅ T+1 訓練完成")
    except subprocess.CalledProcessError as e:
        print(f"[Error] T+1 訓練失敗: {e}")
        return False
    except FileNotFoundError:
        print(f"[Error] 找不到訓練腳本: {script_1d_path}")
        return False

    # 3. 封存模型
    print("\n[Archive] 封存模型到當日工作區...")
    
    def archive_dir(src_dir, dest_dir):
        if os.path.exists(src_dir):
            if os.path.exists(dest_dir):
                shutil.rmtree(dest_dir)
            shutil.copytree(src_dir, dest_dir)
            print(f"  ✅ 已封存: {os.path.basename(src_dir)} -> {dest_dir}")
        else:
            print(f"  ⚠️ 來源目錄不存在: {src_dir}")

    archive_dir(DEFAULT_LSTM_5D_DIR, workspace['lstm_5d'])
    archive_dir(DEFAULT_LSTM_1D_DIR, workspace['lstm_1d'])
    
    return True


# =============================================================================
# Step 2: 隔離式特徵工程 (使用當日重訓的 LSTM)
# =============================================================================
def isolated_feature_engineering(workspace: dict, end_date: str) -> pd.DataFrame:
    print("\n" + "=" * 60)
    print("🔧 Step 2: 特徵工程 (使用當日重訓的 LSTM)")
    print("=" * 60)
    
    # 引用 SelfAttention 類別
    try:
        from twii_model_registry_5d import SelfAttention
        print("[System] 成功引用原始 SelfAttention 類別")
    except ImportError:
        print("[Error] 無法引用 twii_model_registry_5d")
        sys.exit(1)

    # 輔助函式：載入整組模型元件
    def load_model_components(model_dir):
        keras_files = glob.glob(os.path.join(model_dir, "*.keras"))
        if not keras_files: return None, None, None, None
        
        latest_keras = sorted(keras_files)[-1]
        print(f"  ...Loading {os.path.basename(latest_keras)}")
        
        model = keras.models.load_model(latest_keras, custom_objects={'SelfAttention': SelfAttention})

        # 載入 Meta
        meta_file = latest_keras.replace('model_', 'meta_').replace('.keras', '.json')
        meta = {}
        if os.path.exists(meta_file):
            try:
                with open(meta_file, 'r', encoding='utf-8') as f:
                    meta = json.load(f)
            except Exception as e:
                print(f"  ⚠️ 載入 meta 失敗: {e}")

        # 載入 Feature Scaler
        scaler_feat_file = latest_keras.replace('model_', 'feature_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_feat_file):
             scaler_feat_file = latest_keras.replace('model_', 'scaler_').replace('.keras', '.pkl')
        
        scaler_feat = None
        if os.path.exists(scaler_feat_file):
            with open(scaler_feat_file, 'rb') as f:
                scaler_feat = pickle.load(f)

        # 載入 Target Scaler
        scaler_tgt_file = latest_keras.replace('model_', 'target_scaler_').replace('.keras', '.pkl')
        if not os.path.exists(scaler_tgt_file):
             scaler_tgt = scaler_feat
        else:
             with open(scaler_tgt_file, 'rb') as f:
                 scaler_tgt = pickle.load(f)

        return model, scaler_feat, scaler_tgt, meta

    # 1. 載入當日重訓的模型
    print("\n[Model Injection] 載入當日重訓的 LSTM 模型...")
    m5d, sf5d, st5d, meta5d = load_model_components(workspace['lstm_5d'])
    m1d, sf1d, st1d, meta1d = load_model_components(workspace['lstm_1d'])
    
    if m5d is None or m1d is None:
        print("[Error] 模型載入失敗")
        sys.exit(1)

    # 2. 注入主系統
    print("\n[Model Injection] 注入 core_system._LSTM_MODELS...")
    if not hasattr(core_system, '_LSTM_MODELS'):
        core_system._LSTM_MODELS = {}
    
    core_system._LSTM_MODELS.update({
        'model_5d': m5d, 'scaler_feat_5d': sf5d, 'scaler_tgt_5d': st5d, 'meta_5d': meta5d,
        'model_1d': m1d, 'scaler_feat_1d': sf1d, 'scaler_tgt_1d': st1d, 'meta_1d': meta1d,
        'loaded': True
    })
    print("  ✅ 當日 LSTM 模型注入完成")

    # 3. 下載數據 & 計算特徵
    end_dt = datetime.strptime(end_date, '%Y-%m-%d') + timedelta(days=1)
    print(f"\n[Compute] Loading Data (2020-01-01 ~ {end_date})...")
    
    raw_df = core_system._load_local_twii_data(start_date="2020-01-01")
    
    end_dt_ts = pd.Timestamp(end_date)
    raw_df = raw_df[raw_df.index <= end_dt_ts]
    
    actual_last_date = raw_df.index[-1].strftime('%Y-%m-%d')
    print(f"[Data] 實際資料最後日期: {actual_last_date}")
    
    # 匯出原始數據 CSV
    raw_csv_path = os.path.join(workspace['cache'], 'raw_data.csv')
    raw_df.to_csv(raw_csv_path)
    print(f"[Export] 原始數據已存檔: {raw_csv_path}")
    
    print(f"[Compute] 計算特徵中 (使用當日重訓的 LSTM)...")
    df = core_system.calculate_features(raw_df, raw_df, ticker="^TWII", use_cache=False)
    
    # 匯出處理後特徵數據 CSV
    features_csv_path = os.path.join(workspace['cache'], 'processed_features.csv')
    df.to_csv(features_csv_path)
    print(f"[Export] 特徵數據已存檔: {features_csv_path}")
    
    # 存入當日快取
    cache_file = os.path.join(workspace['cache'], 'twii_features.pkl')
    with open(cache_file, 'wb') as f:
        pickle.dump(df, f)
    print(f"[Cache] 特徵已存檔: {cache_file}")
    
    return df, actual_last_date


# =============================================================================
# Step 3: Rolling V4 模型推論 (與 daily_ops_v4_rolling.py 相同)
# =============================================================================
def rolling_v4_inference(workspace: dict, df: pd.DataFrame) -> dict:
    print("\n" + "=" * 60)
    print("🎯 Step 3: Rolling V4 模型推論 (含濾網與情境分析)")
    print("=" * 60)
    
    from stable_baselines3 import PPO
    
    # 準備特徵
    FEATURE_COLS = core_system.FEATURE_COLS
    latest = df.iloc[-1]
    
    # 獲取濾網狀態
    signal_buy_filter = bool(latest.get('Signal_Buy_Filter', False))
    print(f"  [濾網] Signal_Buy_Filter = {signal_buy_filter}")
    
    # 確保特徵欄位對齊
    features = []
    for col in FEATURE_COLS:
        val = latest.get(col, 0.0)
        features.append(val)
    features = np.array(features, dtype=np.float32).reshape(1, -1)
    
    # 處理 NaN/Inf
    features = np.nan_to_num(features, nan=0.0, posinf=1.0, neginf=-1.0)
    
    results = {'filter_status': signal_buy_filter}
    
    # 三種持倉情境
    SELL_SCENARIOS = {
        'cost': 1.00,
        'profit': 1.10,
        'loss': 0.95,
    }
    
    # 載入 Rolling V4 模型
    buy_path = os.path.join(ROLLING_RL_PATH, 'ppo_buy_twii_final.zip')
    sell_path = os.path.join(ROLLING_RL_PATH, 'ppo_sell_twii_final.zip')
    
    if not os.path.exists(buy_path):
        results['V4_Rolling'] = {'error': 'Model not found'}
        print(f"[Error] Rolling V4 模型不存在: {buy_path}")
        return results

    try:
        buy_agent = PPO.load(buy_path)
        sell_agent = PPO.load(sell_path)
        
        # Buy Logic
        b_act, _ = buy_agent.predict(features, deterministic=True)
        b_obs = buy_agent.policy.obs_to_tensor(features)[0]
        b_prob = buy_agent.policy.get_distribution(b_obs).distribution.probs.detach().cpu().numpy()[0]
        
        ai_action = 'BUY' if b_act[0] == 1 else 'WAIT'
        buy_prob = float(b_prob[1]) if b_act[0] == 1 else float(b_prob[0])
        
        if signal_buy_filter:
            buy_signal = ai_action
        else:
            buy_signal = f"FILTERED (AI: {ai_action})"
        
        print(f"  [V4 Rolling] Buy: {buy_signal} ({buy_prob:.1%})")
        
        # Sell Logic
        sell_scenarios = {}
        for scenario_name, return_value in SELL_SCENARIOS.items():
            s_feat = np.concatenate([features[0], [return_value]]).reshape(1, -1)
            s_act, _ = sell_agent.predict(s_feat, deterministic=True)
            sell_scenarios[scenario_name] = 'SELL' if s_act[0] == 1 else 'HOLD'
        
        print(f"  [V4 Rolling] Sell: 成本={sell_scenarios['cost']} | 獲利={sell_scenarios['profit']} | 虧損={sell_scenarios['loss']}")
        
        results['V4_Rolling'] = {
            'name': 'V4 Rolling LSTM (Daily Retrain)',
            'buy_signal': buy_signal,
            'buy_prob': buy_prob,
            'ai_action': ai_action,
            'sell_scenarios': sell_scenarios,
        }
        
    except Exception as e:
        results['V4_Rolling'] = {'error': str(e)}
        print(f"[Error] V4 Rolling: {e}")
        import traceback
        traceback.print_exc()

    return results


# =============================================================================
# Step 4: 輸出報告
# =============================================================================
def generate_report(workspace: dict, df: pd.DataFrame, res: dict, date_str: str):
    print("\n" + "=" * 60)
    print("📊 Step 4: 戰情儀表板 (Rolling V4 + Daily Retrain)")
    print("=" * 60)
    
    last = df.iloc[-1]
    filter_status = res.get('filter_status', False)
    
    lines = []
    lines.append("=" * 50)
    lines.append(f"📅 日期: {date_str}")
    lines.append("=" * 50)
    lines.append(f"📊 收盤: {last['Close']:.2f} | 量: {last['Volume']:.2f} 億元")
    lines.append("-" * 50)
    
    # 標注這是每日重訓版
    lines.append("⚙️ [模式] 每日 LSTM 重訓版")
    lines.append("-" * 50)
    
    # 濾網狀態
    filter_icon = "✅" if filter_status else "🚫"
    filter_text = "通過 (Donchian 突破)" if filter_status else "未通過 (非突破日)"
    lines.append(f"🚦 [濾網狀態] {filter_icon} {filter_text}")
    lines.append("-" * 50)
    
    # LSTM
    lines.append("🔮 [分析師 LSTM - 當日重訓]")
    lines.append(f"   T+1 漲跌: {last.get('LSTM_Pred_1d', 0)*100:+.2f}% (信心度: {last.get('LSTM_Conf_1d', 0)*100:.1f}%)")
    lines.append(f"   T+5 漲跌: {last.get('LSTM_Pred_5d', 0)*100:+.2f}% (信心度: {last.get('LSTM_Conf_5d', 0)*100:.1f}%)")
    lines.append("-" * 50)
    
    # RL 策略
    lines.append("🤖 [操盤手 RL - Rolling V4]")
    
    r = res.get('V4_Rolling', {})
    if 'error' in r:
        lines.append(f"   V4 Rolling: ❌ 模型載入失敗")
    else:
        buy_signal = r['buy_signal']
        buy_prob = r['buy_prob']
        
        if buy_signal == 'BUY':
            buy_icon = "🚀"
        elif buy_signal == 'WAIT':
            buy_icon = "💤"
        elif 'FILTERED' in buy_signal:
            buy_icon = "🚫"
        else:
            buy_icon = "❓"
        
        lines.append(f"   🛒 買入: {buy_icon} {buy_signal} ({buy_prob:.1%})")
        
        ss = r.get('sell_scenarios', {})
        lines.append(f"   📦 賣出:")
        lines.append(f"      ├─ 成本區 (0%):  {ss.get('cost', 'N/A')}")
        lines.append(f"      ├─ 獲利中 (+10%): {ss.get('profit', 'N/A')}")
        lines.append(f"      └─ 虧損中 (-5%):  {ss.get('loss', 'N/A')}")
    
    lines.append("-" * 50)
    
    # 綜合建議
    ai_action = res.get('V4_Rolling', {}).get('ai_action', 'N/A')
    
    if not filter_status:
        if ai_action == 'BUY':
            advice = "🚫 濾網攔截 | AI 意圖: 買進 (被擋下)"
        else:
            advice = "🚫 濾網攔截 | AI 意圖: 觀望"
    elif ai_action == 'BUY':
        advice = "⭐ V4 Rolling 買進 (Buy) ⭐"
    else:
        advice = "💤 空手觀望 (Wait)"
        
    lines.append(f"💡 綜合建議: {advice}")
    lines.append("=" * 50)
    
    report = "\n".join(lines)
    print(report)
    
    # 存檔 TXT
    txt_path = os.path.join(workspace['reports'], 'summary.txt')
    with open(txt_path, 'w', encoding='utf-8') as f:
        f.write(report)
    
    # 存檔 JSON
    json_path = os.path.join(workspace['reports'], 'summary.json')
    json_data = {
        'date': date_str,
        'generated_at': datetime.now().isoformat(),
        'mode': 'daily_retrain',
        'filter_status': filter_status,
        'market': {
            'close': float(last.get('Close', 0)),
            'volume': float(last.get('Volume', 0)),
        },
        'lstm': {
            'pred_1d': float(last.get('LSTM_Pred_1d', 0)),
            'conf_1d': float(last.get('LSTM_Conf_1d', 0)),
            'pred_5d': float(last.get('LSTM_Pred_5d', 0)),
            'conf_5d': float(last.get('LSTM_Conf_5d', 0)),
        },
        'strategy': res.get('V4_Rolling', {}),
        'advice': advice,
    }
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(json_data, f, indent=2, ensure_ascii=False)
    
    print(f"\n[Report] 已儲存: {txt_path}")
    print(f"[Report] 已儲存: {json_path}")


# =============================================================================
# Main
# =============================================================================
def main():
    today = datetime.now()
    # 處理週末
    if today.weekday() == 5: today -= timedelta(days=1)
    elif today.weekday() == 6: today -= timedelta(days=2)
    
    date_str = today.strftime('%Y-%m-%d')
    print(f"🚀 啟動 Rolling V4 每日維運系統 (每日重訓版) - {date_str}")
    
    # Step 0: 建立工作區
    ws = create_daily_workspace(date_str)
    
    # Step 1: LSTM 每日重訓 ⚠️ 這是與 daily_ops_v4_rolling.py 的主要差異
    train_and_archive_lstm(ws, date_str)
    
    # Step 2: 特徵工程
    df, actual_date = isolated_feature_engineering(ws, date_str)
    
    if actual_date != date_str:
        print(f"[Warning] 預估日期 {date_str} 與實際資料日期 {actual_date} 不同")
        print(f"[Info] 報告將使用實際資料日期: {actual_date}")
    
    # Step 3: 模型推論
    res = rolling_v4_inference(ws, df)
    
    # Step 4: 輸出報告
    generate_report(ws, df, res, actual_date)
    
    print("\n✅ Rolling V4 Daily Ops (每日重訓版) 執行完成！")


if __name__ == "__main__":
    main()
