#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
V4 Rolling LSTM Training Script
================================================================================
Rolling LSTM Update Strategy：
- RL 訓練期間，每年更新一次 LSTM 模型
- LSTM 永遠只用 RL 當前訓練年份之前的資料訓練
- 確保 RL 看到的 LSTM 預測都是 out-of-sample

LSTM 窗口設定 (與 daily_ops_dual.py 實戰一致)：
- T+5: 2200 天 (~6 年)
- T+1: 2000 天 (~5.5 年)

作者：Phil Liang (Generated by Gemini)
日期：2025-12-12
================================================================================
"""

import os
import sys
import argparse
import subprocess
import pickle
import glob
import shutil
from datetime import datetime, timedelta
from pathlib import Path

# Windows 終端機 UTF-8 編碼設定
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = Path(__file__).parent
CACHE_DIR = PROJECT_PATH / "data" / "processed"
DATA_PATH = PROJECT_PATH / "data" / "raw"

# LSTM 模型預設輸出路徑
DEFAULT_LSTM_5D_DIR = PROJECT_PATH / "saved_models_5d"
DEFAULT_LSTM_1D_DIR = PROJECT_PATH / "saved_models_multivariate"

# Rolling LSTM 專用模型儲存路徑
ROLLING_LSTM_DIR = PROJECT_PATH / "rolling_lstm_models"

# RL 模型輸出路徑
V4_ROLLING_MODELS_PATH = PROJECT_PATH / "models_hybrid_v4_rolling"
V4_ROLLING_RESULTS_PATH = PROJECT_PATH / "results_hybrid_v4_rolling"

# LSTM 訓練腳本
SCRIPT_5D = "twii_model_registry_5d.py"
SCRIPT_1D = "twii_model_registry_multivariate.py"

# LSTM 窗口設定 (日曆天數，與實戰一致)
LSTM_WINDOW_5D = 2200  # ~6 年
LSTM_WINDOW_1D = 2000  # ~5.5 年

# RL 訓練設定
RL_START_YEAR = 2006  # 最早可開始的年份 (因 T+5 需要 6 年歷史)
RL_END_YEAR = 2022    # 訓練結束年份 (驗證期從 2023 開始)
SPLIT_DATE = '2023-01-01'

# 微調步數 (與 V4 一致)
FINETUNE_BUY_STEPS_PER_YEAR = 60_000   # 每年約 60K 步
FINETUNE_SELL_STEPS_PER_YEAR = 20_000  # 每年約 20K 步


# =============================================================================
# 輔助函數
# =============================================================================
def calculate_lstm_dates(rl_year: int) -> dict:
    """
    計算指定 RL 訓練年份對應的 LSTM 訓練日期範圍
    
    Args:
        rl_year: RL 訓練的目標年份 (e.g., 2010)
    
    Returns:
        dict 包含 T+5 和 T+1 的起始/結束日期
    """
    # LSTM 訓練結束日 = RL 年份前一年底
    end_date = datetime(rl_year - 1, 12, 31)
    
    # 計算起始日期
    start_5d = end_date - timedelta(days=LSTM_WINDOW_5D)
    start_1d = end_date - timedelta(days=LSTM_WINDOW_1D)
    
    return {
        'end_date': end_date.strftime('%Y-%m-%d'),
        'start_5d': start_5d.strftime('%Y-%m-%d'),
        'start_1d': start_1d.strftime('%Y-%m-%d'),
    }


def train_lstm_for_year(rl_year: int, dry_run: bool = False) -> bool:
    """
    訓練指定年份對應的 LSTM 模型
    
    Args:
        rl_year: RL 訓練的目標年份
        dry_run: 若為 True，只顯示計畫不實際執行
    
    Returns:
        是否成功
    """
    dates = calculate_lstm_dates(rl_year)
    
    print(f"\n{'='*60}")
    print(f"📅 LSTM Training for RL Year {rl_year}")
    print(f"{'='*60}")
    print(f"  LSTM 訓練結束日: {dates['end_date']}")
    print(f"  T+5 訓練起始日: {dates['start_5d']} ({LSTM_WINDOW_5D} 天)")
    print(f"  T+1 訓練起始日: {dates['start_1d']} ({LSTM_WINDOW_1D} 天)")
    
    if dry_run:
        print("  [Dry Run] 跳過實際訓練")
        return True
    
    # 創建年度專屬目錄
    year_lstm_dir = ROLLING_LSTM_DIR / str(rl_year)
    year_lstm_5d_dir = year_lstm_dir / "saved_models_5d"
    year_lstm_1d_dir = year_lstm_dir / "saved_models_multivariate"
    year_lstm_dir.mkdir(parents=True, exist_ok=True)
    year_lstm_5d_dir.mkdir(exist_ok=True)
    year_lstm_1d_dir.mkdir(exist_ok=True)
    
    split_ratio = "0.99"  # 與實戰一致
    
    # 1. 訓練 T+5
    print(f"\n[Training] T+5 Model ({dates['start_5d']} ~ {dates['end_date']})...")
    cmd_5d = [
        sys.executable, str(PROJECT_PATH / SCRIPT_5D), "train",
        "--start", dates['start_5d'],
        "--end", dates['end_date'],
        "--split_ratio", split_ratio
    ]
    
    try:
        subprocess.run(cmd_5d, check=True, timeout=1800, cwd=PROJECT_PATH)
        print("[Training] ✅ T+5 訓練完成")
        
        # 複製到年度目錄
        if DEFAULT_LSTM_5D_DIR.exists():
            for f in DEFAULT_LSTM_5D_DIR.glob("*"):
                shutil.copy2(f, year_lstm_5d_dir)
            print(f"  ✅ 已封存到 {year_lstm_5d_dir}")
    except Exception as e:
        print(f"[Error] T+5 訓練失敗: {e}")
        return False
    
    # 2. 訓練 T+1
    print(f"\n[Training] T+1 Model ({dates['start_1d']} ~ {dates['end_date']})...")
    cmd_1d = [
        sys.executable, str(PROJECT_PATH / SCRIPT_1D), "train",
        "--start", dates['start_1d'],
        "--end", dates['end_date'],
        "--split_ratio", split_ratio
    ]
    
    try:
        subprocess.run(cmd_1d, check=True, timeout=1800, cwd=PROJECT_PATH)
        print("[Training] ✅ T+1 訓練完成")
        
        # 複製到年度目錄
        if DEFAULT_LSTM_1D_DIR.exists():
            for f in DEFAULT_LSTM_1D_DIR.glob("*"):
                shutil.copy2(f, year_lstm_1d_dir)
            print(f"  ✅ 已封存到 {year_lstm_1d_dir}")
    except Exception as e:
        print(f"[Error] T+1 訓練失敗: {e}")
        return False
    
    return True


def load_lstm_models_for_year(rl_year: int):
    """
    載入指定年份的 LSTM 模型並注入到 core_system
    
    Args:
        rl_year: RL 訓練的目標年份
    """
    import ptrl_hybrid_system as core_system
    from tensorflow import keras
    
    try:
        from twii_model_registry_5d import SelfAttention
    except ImportError:
        print("[Error] 無法引用 SelfAttention 類別")
        return False
    
    year_lstm_dir = ROLLING_LSTM_DIR / str(rl_year)
    lstm_5d_dir = year_lstm_dir / "saved_models_5d"
    lstm_1d_dir = year_lstm_dir / "saved_models_multivariate"
    
    def load_model_components(model_dir):
        keras_files = list(Path(model_dir).glob("*.keras"))
        if not keras_files:
            return None, None, None, None
        
        latest_keras = sorted(keras_files)[-1]
        model = keras.models.load_model(str(latest_keras), custom_objects={'SelfAttention': SelfAttention})
        
        # 載入 Scalers
        scaler_feat_file = str(latest_keras).replace('model_', 'feature_scaler_').replace('.keras', '.pkl')
        scaler_tgt_file = str(latest_keras).replace('model_', 'target_scaler_').replace('.keras', '.pkl')
        meta_file = str(latest_keras).replace('model_', 'meta_').replace('.keras', '.json')
        
        scaler_feat, scaler_tgt, meta = None, None, {}
        
        if os.path.exists(scaler_feat_file):
            with open(scaler_feat_file, 'rb') as f:
                scaler_feat = pickle.load(f)
        
        if os.path.exists(scaler_tgt_file):
            with open(scaler_tgt_file, 'rb') as f:
                scaler_tgt = pickle.load(f)
        else:
            scaler_tgt = scaler_feat
        
        if os.path.exists(meta_file):
            import json
            with open(meta_file, 'r', encoding='utf-8') as f:
                meta = json.load(f)
        
        return model, scaler_feat, scaler_tgt, meta
    
    print(f"\n[Model Injection] 載入 {rl_year} 年的 LSTM 模型...")
    
    m5d, sf5d, st5d, meta5d = load_model_components(lstm_5d_dir)
    m1d, sf1d, st1d, meta1d = load_model_components(lstm_1d_dir)
    
    if m5d is None or m1d is None:
        print(f"[Error] 找不到 {rl_year} 年的 LSTM 模型")
        return False
    
    # 注入主系統
    if not hasattr(core_system, '_LSTM_MODELS'):
        core_system._LSTM_MODELS = {}
    
    core_system._LSTM_MODELS.update({
        'model_5d': m5d, 'scaler_feat_5d': sf5d, 'scaler_tgt_5d': st5d, 'meta_5d': meta5d,
        'model_1d': m1d, 'scaler_feat_1d': sf1d, 'scaler_tgt_1d': st1d, 'meta_1d': meta1d,
        'loaded': True
    })
    
    print(f"  ✅ {rl_year} 年 LSTM 模型注入完成")
    return True


def run_rolling_finetuning(start_year: int, end_year: int, dry_run: bool = False):
    """
    執行 Rolling LSTM 微調訓練
    
    Args:
        start_year: 起始年份
        end_year: 結束年份
        dry_run: 若為 True，只顯示計畫不實際執行
    """
    import ptrl_hybrid_system as hybrid
    import pandas as pd
    import torch
    
    print("\n" + "=" * 70)
    print("🚀 Rolling LSTM Fine-tuning Strategy")
    print("=" * 70)
    print(f"  訓練年份範圍: {start_year} ~ {end_year}")
    print(f"  LSTM 窗口: T+5={LSTM_WINDOW_5D}天, T+1={LSTM_WINDOW_1D}天")
    print("=" * 70)
    
    if dry_run:
        print("\n📋 [Dry Run Mode] 訓練計畫預覽：")
        for year in range(start_year, end_year + 1):
            dates = calculate_lstm_dates(year)
            print(f"\n年度 {year}:")
            print(f"  - LSTM T+5: {dates['start_5d']} ~ {dates['end_date']}")
            print(f"  - LSTM T+1: {dates['start_1d']} ~ {dates['end_date']}")
            print(f"  - RL 訓練: {year}-01-01 ~ {year}-12-31")
        print("\n[Dry Run] 完成預覽，未執行實際訓練。")
        return
    
    # 創建輸出目錄
    V4_ROLLING_MODELS_PATH.mkdir(parents=True, exist_ok=True)
    V4_ROLLING_RESULTS_PATH.mkdir(parents=True, exist_ok=True)
    
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\n[System] Device: {device}")
    
    # 載入完整 TWII 資料
    print("\n[Data] Loading ^TWII from local CSV...")
    twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
    
    # 檢查是否有預訓練模型
    buy_base_path = V4_ROLLING_MODELS_PATH / "ppo_buy_base.zip"
    if not buy_base_path.exists():
        print("\n[Warning] 未找到預訓練模型，需先執行預訓練...")
        print("請先執行: python train_v4_models.py (預訓練部分)")
        print("或複製現有的 ppo_buy_base.zip 和 ppo_sell_base.zip 到:")
        print(f"  {V4_ROLLING_MODELS_PATH}")
        return
    
    # 年度滾動訓練
    for year in range(start_year, end_year + 1):
        print("\n" + "=" * 70)
        print(f"📅 Year {year} / {end_year}")
        print("=" * 70)
        
        # Step 1: 訓練 LSTM
        success = train_lstm_for_year(year, dry_run=False)
        if not success:
            print(f"[Error] LSTM 訓練失敗於 {year} 年，終止訓練")
            return
        
        # Step 2: 載入 LSTM 模型
        success = load_lstm_models_for_year(year)
        if not success:
            print(f"[Error] LSTM 模型載入失敗於 {year} 年，終止訓練")
            return
        
        # Step 3: 計算該年度特徵
        print(f"\n[Feature] 計算 {year} 年特徵...")
        year_start = pd.Timestamp(f"{year}-01-01")
        year_end = pd.Timestamp(f"{year}-12-31")
        
        # 篩選該年度資料
        year_df = twii_raw[(twii_raw.index >= year_start) & (twii_raw.index <= year_end)]
        
        if len(year_df) == 0:
            print(f"[Warning] {year} 年無資料，跳過")
            continue
        
        # 需要更多歷史資料來計算特徵
        feature_start = year_start - pd.Timedelta(days=365)
        extended_df = twii_raw[(twii_raw.index >= feature_start) & (twii_raw.index <= year_end)]
        
        # 計算特徵 (使用當年的 LSTM 模型)
        features_df = hybrid.calculate_features(extended_df, extended_df, ticker="^TWII", use_cache=False)
        
        # 只取該年度的資料
        year_features = features_df[(features_df.index >= year_start) & (features_df.index <= year_end)]
        
        print(f"  資料筆數: {len(year_features)}")
        
        # Step 4: RL 微調
        print(f"\n[Fine-tune] 訓練 {year} 年 RL 模型...")
        
        from stable_baselines3 import PPO
        from stable_baselines3.common.env_util import make_vec_env
        from stable_baselines3.common.vec_env import SubprocVecEnv
        import multiprocessing
        
        # 使用多環境並行訓練 (提高 FPS)
        n_envs = min(8, max(1, multiprocessing.cpu_count() - 1))
        
        finetune_data = {'^TWII': year_features}
        
        # 計算該年度的訓練步數 (根據資料量調整)
        data_ratio = len(year_features) / 250  # 250 = 一年約交易日
        buy_steps = int(FINETUNE_BUY_STEPS_PER_YEAR * data_ratio)
        sell_steps = int(FINETUNE_SELL_STEPS_PER_YEAR * data_ratio)
        
        print(f"  Buy 步數: {buy_steps:,} | Sell 步數: {sell_steps:,}")
        
        # 載入上一年的模型或基礎模型
        if year == start_year:
            buy_model_path = V4_ROLLING_MODELS_PATH / "ppo_buy_base.zip"
            sell_model_path = V4_ROLLING_MODELS_PATH / "ppo_sell_base.zip"
        else:
            buy_model_path = V4_ROLLING_MODELS_PATH / f"ppo_buy_{year-1}.zip"
            sell_model_path = V4_ROLLING_MODELS_PATH / f"ppo_sell_{year-1}.zip"
        
        # Buy Agent 訓練
        try:
            buy_env = make_vec_env(
                hybrid.BuyEnvHybrid, n_envs=n_envs, vec_env_cls=SubprocVecEnv,
                env_kwargs={'data_dict': finetune_data, 'is_training': True}
            )
            print(f"  [System] 使用 {n_envs} 個並行環境")
            
            buy_model = PPO.load(str(buy_model_path), env=buy_env, device=device)
            buy_model.learning_rate = 1e-5
            buy_model.learn(total_timesteps=buy_steps, reset_num_timesteps=False)
            
            buy_save_path = V4_ROLLING_MODELS_PATH / f"ppo_buy_{year}.zip"
            buy_model.save(str(buy_save_path))
            buy_env.close()
            
            print(f"  ✅ Buy Agent 已儲存: {buy_save_path.name}")
        except Exception as e:
            print(f"  ❌ Buy Agent 訓練失敗: {e}")
            return
        
        # Sell Agent 訓練
        try:
            sell_env = make_vec_env(
                hybrid.SellEnvHybrid, n_envs=n_envs, vec_env_cls=SubprocVecEnv,
                env_kwargs={'data_dict': finetune_data}
            )
            
            sell_model = PPO.load(str(sell_model_path), env=sell_env, device=device)
            sell_model.learning_rate = 1e-5
            sell_model.learn(total_timesteps=sell_steps, reset_num_timesteps=False)
            
            sell_save_path = V4_ROLLING_MODELS_PATH / f"ppo_sell_{year}.zip"
            sell_model.save(str(sell_save_path))
            sell_env.close()
            
            print(f"  ✅ Sell Agent 已儲存: {sell_save_path.name}")
        except Exception as e:
            print(f"  ❌ Sell Agent 訓練失敗: {e}")
            return
    
    # 複製最終模型為 final
    final_buy = V4_ROLLING_MODELS_PATH / f"ppo_buy_{end_year}.zip"
    final_sell = V4_ROLLING_MODELS_PATH / f"ppo_sell_{end_year}.zip"
    
    if final_buy.exists():
        shutil.copy2(final_buy, V4_ROLLING_MODELS_PATH / "ppo_buy_twii_final.zip")
    if final_sell.exists():
        shutil.copy2(final_sell, V4_ROLLING_MODELS_PATH / "ppo_sell_twii_final.zip")
    
    print("\n" + "=" * 70)
    print("✅ Rolling LSTM Training Completed!")
    print("=" * 70)
    print(f"  模型儲存位置: {V4_ROLLING_MODELS_PATH}")
    print(f"  最終模型: ppo_buy_twii_final.zip, ppo_sell_twii_final.zip")
    print("=" * 70)


def main():
    parser = argparse.ArgumentParser(description="V4 Rolling LSTM Training Script")
    parser.add_argument("--dry-run", action="store_true", help="只顯示訓練計畫，不實際執行")
    parser.add_argument("--start-year", type=int, default=RL_START_YEAR, help=f"起始年份 (default: {RL_START_YEAR})")
    parser.add_argument("--end-year", type=int, default=RL_END_YEAR, help=f"結束年份 (default: {RL_END_YEAR})")
    parser.add_argument("--lstm-only", action="store_true", help="只訓練 LSTM 模型，不訓練 RL")
    
    args = parser.parse_args()
    
    print("=" * 70)
    print("V4 Rolling LSTM Training Script")
    print("=" * 70)
    
    if args.lstm_only:
        # 只訓練 LSTM
        for year in range(args.start_year, args.end_year + 1):
            train_lstm_for_year(year, dry_run=args.dry_run)
    else:
        # 完整滾動訓練
        run_rolling_finetuning(args.start_year, args.end_year, dry_run=args.dry_run)


if __name__ == "__main__":
    main()
