#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
================================================================================
V3 模型訓練腳本 - 輕量化微調版本 (Lightweight)
================================================================================
本腳本執行完整的 V3 訓練流程：
1. 清除舊的特徵快取（強制用新的 30 次 MC Dropout 採樣重算）
2. 執行預訓練 (Pre-training)
3. 執行微調 (Fine-tuning) - 輕量化步數

與 V4 的差異：
- Buy Agent Fine-tune: 200K 步 (輕量化)
- Sell Agent Fine-tune: 100K 步 (輕量化)

作者：Phil Liang (Generated by Gemini)
日期：2025-12-07
================================================================================
"""

import os
import sys
import glob
import shutil
import pickle

# 確保能引用 ptrl_hybrid_system
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# 設定 TensorFlow 日誌等級
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

import yfinance as yf
import pandas as pd

# =============================================================================
# 設定
# =============================================================================
PROJECT_PATH = os.path.dirname(os.path.abspath(__file__))
CACHE_DIR = os.path.join(PROJECT_PATH, "data", "processed")
DATA_PATH = os.path.join(PROJECT_PATH, "data", "raw")
V3_MODELS_PATH = os.path.join(PROJECT_PATH, "models_hybrid_v3")
V3_RESULTS_PATH = os.path.join(PROJECT_PATH, "results_hybrid_v3")
SPLIT_DATE = '2023-01-01'

# 訓練步數設定
PRETRAIN_BUY_STEPS = 1_000_000
PRETRAIN_SELL_STEPS = 500_000
# V3: 輕量化微調步數
FINETUNE_BUY_STEPS = 200_000
FINETUNE_SELL_STEPS = 100_000


def clear_cache():
    """Step A: 清除特徵快取"""
    print("\n" + "=" * 60)
    print("🧹 Step A: 清除特徵快取")
    print("=" * 60)
    
    if not os.path.exists(CACHE_DIR):
        print(f"[Info] 快取目錄不存在: {CACHE_DIR}")
        return
    
    pkl_files = glob.glob(os.path.join(CACHE_DIR, "*.pkl"))
    
    if not pkl_files:
        print("[Info] 沒有找到 .pkl 快取檔案")
        return
    
    print(f"[Info] 找到 {len(pkl_files)} 個快取檔案")
    
    for f in pkl_files:
        try:
            os.remove(f)
            print(f"  ✅ 已刪除: {os.path.basename(f)}")
        except Exception as e:
            print(f"  ⚠️ 刪除失敗: {os.path.basename(f)} - {e}")
    
    print("[Done] 快取清除完成")


def run_pretraining():
    """Step B: 預訓練"""
    print("\n" + "=" * 60)
    print("🎓 Step B: 預訓練 (Pre-training)")
    print("=" * 60)
    print(f"  Buy Agent:  {PRETRAIN_BUY_STEPS:,} steps")
    print(f"  Sell Agent: {PRETRAIN_SELL_STEPS:,} steps")
    print(f"  輸出路徑:   {V3_MODELS_PATH}")
    print("=" * 60)
    
    # 確保輸出目錄存在
    os.makedirs(V3_MODELS_PATH, exist_ok=True)
    os.makedirs(DATA_PATH, exist_ok=True)
    
    # 引用主系統
    import ptrl_hybrid_system as hybrid
    
    # 檢測裝置
    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[System] 使用裝置: {device}")
    
    # 載入 LSTM 模型
    print("\n[System] 載入 LSTM 模型...")
    hybrid.load_best_lstm_models()
    
    # 準備訓練資料 (使用正確的 API)
    print("\n[Data] 下載全球指數資料...")
    raw_data = hybrid.fetch_index_data(DATA_PATH, start_date="2000-01-01", end_date=SPLIT_DATE)
    
    print("\n[Data] 計算特徵 (使用新的 30 次 MC Dropout 採樣)...")
    train_data = {}
    benchmark_df = raw_data.get("^TWII")
    for ticker, df in raw_data.items():
        try:
            processed = hybrid.calculate_features(df, benchmark_df, ticker, use_cache=False)  # 不用快取
            if len(processed) > 100:
                train_data[ticker] = processed
                print(f"  ✅ {ticker}: {len(processed)} rows")
        except Exception as e:
            print(f"  ⚠️ {ticker}: {e}")
    
    # 執行預訓練
    print(f"\n[Training] 開始預訓練...")
    hybrid.run_pretraining(train_data, V3_MODELS_PATH, device)
    
    print(f"\n[Done] 預訓練完成！模型已儲存至 {V3_MODELS_PATH}/")


def run_finetuning():
    """Step C: 微調 (輕量化)"""
    print("\n" + "=" * 60)
    print("🎯 Step C: 微調 (Fine-tuning - 輕量化)")
    print("=" * 60)
    print(f"  Buy Agent:  {FINETUNE_BUY_STEPS:,} steps (輕量化)")
    print(f"  Sell Agent: {FINETUNE_SELL_STEPS:,} steps (輕量化)")
    print(f"  輸出路徑:   {V3_MODELS_PATH}")
    print("=" * 60)
    
    # 引用主系統
    import ptrl_hybrid_system as hybrid
    
    # 檢測裝置
    import torch
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"[System] 使用裝置: {device}")
    
    # 載入 LSTM 模型 (如果還沒載入)
    hybrid.load_best_lstm_models()
    
    # 準備 TWII 資料
    print("\n[Data] 準備 ^TWII 資料...")
    cache_path = os.path.join(CACHE_DIR, "_TWII_features.pkl")
    
    if os.path.exists(cache_path):
        print(f"[Cache] 載入 ^TWII 特徵...")
        with open(cache_path, 'rb') as f:
            twii_full_df = pickle.load(f)
    else:
        print("[Compute] Loading ^TWII from local CSV...")
        # [Modify] 使用本地資料載入函數
        twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
        
        twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=True)
    
    print(f"[Data] ^TWII 資料: {len(twii_full_df)} rows")
    
    # 分割資料
    split_date = pd.Timestamp(SPLIT_DATE)
    twii_finetune_df = twii_full_df[twii_full_df.index < split_date]
    twii_eval_df = twii_full_df[twii_full_df.index >= split_date]
    
    print(f"  Fine-tuning set: {len(twii_finetune_df)} rows (< {SPLIT_DATE})")
    print(f"  Eval set:        {len(twii_eval_df)} rows (>= {SPLIT_DATE})")
    
    finetune_data = {'^TWII': twii_finetune_df}
    eval_data = {'^TWII': twii_eval_df}
    
    # 執行微調 (傳入輕量化步數)
    print(f"\n[Training] 開始微調 (輕量化)...")
    hybrid.run_finetuning(finetune_data, eval_data, V3_MODELS_PATH, device,
                          finetune_buy_steps=FINETUNE_BUY_STEPS,
                          finetune_sell_steps=FINETUNE_SELL_STEPS)
    
    print(f"\n[Done] 微調完成！最終模型已儲存至 {V3_MODELS_PATH}/")


def print_next_steps():
    """印出後續步驟提示"""
    print("\n" + "=" * 60)
    print("✅ V3 模型訓練流程已完成！")
    print("=" * 60)
    print(f"""
📁 模型儲存位置:
   {V3_MODELS_PATH}/ppo_buy_twii_final.zip
   {V3_MODELS_PATH}/ppo_sell_twii_final.zip

� daily_ops_dual.py 已預設使用 V3 和 V4 模型進行雙策略推論
""")


def check_pretrain_complete():
    """檢查預訓練是否完成"""
    buy_base = os.path.join(V3_MODELS_PATH, "ppo_buy_base.zip")
    sell_base = os.path.join(V3_MODELS_PATH, "ppo_sell_base.zip")
    return os.path.exists(buy_base) and os.path.exists(sell_base)


def check_finetune_complete():
    """檢查微調是否完成"""
    buy_final = os.path.join(V3_MODELS_PATH, "ppo_buy_twii_final.zip")
    sell_final = os.path.join(V3_MODELS_PATH, "ppo_sell_twii_final.zip")
    return os.path.exists(buy_final) and os.path.exists(sell_final)


def check_backtest_complete():
    """檢查回測是否完成"""
    result_chart = os.path.join(V3_RESULTS_PATH, "final_performance.png")
    return os.path.exists(result_chart)


def run_backtesting_step():
    """Step D: 回測"""
    print("\n" + "=" * 60)
    print("📊 Step D: 回測 (Backtesting for ^TWII)")
    print("=" * 60)
    print(f"  輸出路徑:   {V3_RESULTS_PATH}")
    print("=" * 60)
    
    # 建立輸出目錄
    os.makedirs(V3_RESULTS_PATH, exist_ok=True)
    
    # 引用主系統
    import ptrl_hybrid_system as hybrid
    from stable_baselines3 import PPO
    
    # 載入 LSTM 模型
    hybrid.load_best_lstm_models()
    
    # 準備 TWII 資料
    print("\n[Data] 準備 ^TWII 資料...")
    cache_path = os.path.join(CACHE_DIR, "_TWII_features.pkl")
    
    if os.path.exists(cache_path):
        print(f"[Cache] 載入 ^TWII 特徵...")
        with open(cache_path, 'rb') as f:
            twii_full_df = pickle.load(f)
    else:
        print("[Compute] Loading ^TWII from local CSV...")
        # [Modify] 使用本地資料載入函數
        twii_raw = hybrid._load_local_twii_data(start_date="2000-01-01")
        twii_full_df = hybrid.calculate_features(twii_raw, twii_raw, ticker="^TWII", use_cache=True)
    
    # 分割資料
    split_date = pd.Timestamp(SPLIT_DATE)
    twii_backtest_df = twii_full_df[twii_full_df.index >= split_date]
    
    print(f"[Data] 回測期間: {twii_backtest_df.index[0].strftime('%Y-%m-%d')} ~ {twii_backtest_df.index[-1].strftime('%Y-%m-%d')}")
    print(f"[Data] 回測資料: {len(twii_backtest_df)} rows")
    
    # 載入 Fine-tuned 模型
    print("\n[Model] 載入 V3 Fine-tuned 模型...")
    buy_model = PPO.load(os.path.join(V3_MODELS_PATH, "ppo_buy_twii_final.zip"))
    sell_model = PPO.load(os.path.join(V3_MODELS_PATH, "ppo_sell_twii_final.zip"))
    
    # 執行回測
    print("\n[Backtest] 執行中...")
    metrics = hybrid.run_backtesting(twii_backtest_df, buy_model, sell_model, V3_RESULTS_PATH, twii_full_df)
    
    print(f"\n[Done] 回測完成！結果已儲存至 {V3_RESULTS_PATH}/")
    return metrics


def main():
    print("=" * 60)
    print("🚀 V3 模型訓練腳本 (輕量化微調版本)")
    print(f"   Buy Fine-tune: {FINETUNE_BUY_STEPS:,} steps | Sell Fine-tune: {FINETUNE_SELL_STEPS:,} steps")
    print("=" * 60)
    
    # Step A: 清除快取 (只在需要時執行)
    # 如果預訓練已完成，不清除快取
    if not check_pretrain_complete():
        clear_cache()
    else:
        print("\n[Skip] Step A: 快取清除 (預訓練已完成，不需清除)")
    
    # Step B: 預訓練 (檢查是否已完成)
    if check_pretrain_complete():
        print("\n" + "=" * 60)
        print("✅ [Skip] Step B: 預訓練已完成")
        print(f"   Buy Base:  {V3_MODELS_PATH}/ppo_buy_base.zip")
        print(f"   Sell Base: {V3_MODELS_PATH}/ppo_sell_base.zip")
        print("=" * 60)
    else:
        run_pretraining()
    
    # Step C: 微調 (檢查是否已完成)
    if check_finetune_complete():
        print("\n" + "=" * 60)
        print("✅ [Skip] Step C: 微調已完成")
        print(f"   Buy Final:  {V3_MODELS_PATH}/ppo_buy_twii_final.zip")
        print(f"   Sell Final: {V3_MODELS_PATH}/ppo_sell_twii_final.zip")
        print("=" * 60)
    else:
        run_finetuning()
    
    # Step D: 回測 (檢查是否已完成)
    if check_backtest_complete():
        print("\n" + "=" * 60)
        print("✅ [Skip] Step D: 回測已完成")
        print(f"   Result: {V3_RESULTS_PATH}/final_performance.png")
        print("=" * 60)
    else:
        run_backtesting_step()
    
    # 印出後續步驟
    print_next_steps()


if __name__ == "__main__":
    main()
